apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: devops
  labels:
    run: jenkins
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: jenkins